[parity]
chain = "./data/spec.json"
base_path = "data/node1"

[network]
port = 30401
nat = "none"
interface = "all"
reserved_peers="data/reserved-peers"

[rpc]
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "personal", "traces"]
port = 8641

[websockets]
interface = "all"
origins = ["all"]
port = 9541

[ipc]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0xbbcaa8d48289bb1ffcf9808d9aa4b1d215054c78", "0x32e4e4c7c5d1cea5db5f9202a9e4d99e56c91a24"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
gas_floor_target = "12000000"
engine_signer = "0xbbcaa8d48289bb1ffcf9808d9aa4b1d215054c78"
reseal_on_txs = "none"
extra_data = "Parity"
tx_gas_limit="7500000"
tx_time_limit=1000

[misc]
logging = "engine=trace,miner=trace,reward=trace"

[footprint]
tracing = "on"
fat_db = "on"
pruning = "archive"
