#!/bin/bash

# Exit on undefined variables.
set -eu

PARITY=$1
NODE=`which node`
cp posdao-contracts/spec.json parity-data/ || exit $?
for i in $(seq 1 9); do
    rm -rf -- "./parity-data/node$i/chains"
    "$PARITY" --config "./config/node${i}.toml" > "./parity-data/node${i}/log" 2>&1 &
done
for i in $(seq 1 9); do
    node ./scripts/getReservedPeer.js "$i"
done
