#!/bin/bash

# Exit on undefined variables.
set -u

PARITY=$1
NODE=`which node`
# $NODE ./scripts/addCandidateBalances.js
for i in 1 2 3; do
    rm -rf -- "./parity-data/node$i/chains"
    "$PARITY" --config "./config/node${i}.toml" > "./parity-data/node${i}/log" 2>&1 &
    "$NODE" ./scripts/getReservedPeer.js "$i"
done
