#!/bin/bash

# Exit on undefined variables.
set -u
set -e

PARITY=$1
for i in $(seq 1 3); do
    "$PARITY" --config "./config/node${i}.toml" >> "./parity-data/node${i}/log" 2>&1 &
    node ./scripts/getReservedPeer.js "$i"
done
