#!/bin/bash

function kill_at_port {
	PID=`lsof -t -i:${1}`
	if [ "$PID" != "" ]; then
        echo Killing pid $PID at port $1
		kill -9 $PID
    else
        echo Nothing to kill at port $1
	fi
}

if [[ -d ./bc/launcher ]]; then
    cd ./bc/launcher
    docker-compose stop validator
    docker-compose stop node2
    docker-compose stop node
    docker-compose down
    cd -
    # docker image rm sigp/lighthouse:v2.1.2-modern
    # docker image rm ghcr.io/gnosischain/deposit-script:latest
fi

# Kill test nodes.
for i in $(seq 0 6); do
    kill_at_port 864$i
done
